version: '2.2'
services:
  elasticsearch0:
    image: elasticsearch:alpine
    container_name: uterus.es0
    environment:
      - cluster.name=prajna-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch1:
    image: elasticsearch:alpine
    container_name: uterus.es1
    environment:
      - cluster.name=prajna-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:alpine
    container_name: uterus.es2
    environment:
      - cluster.name=prajna-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata0:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
